title: Julian | Personal Notes
author: Julian Villella
email: julian.villella@hotmail.com
description: Personal notes, publicly shared.
baseurl: /
twitter_username: JooleanVillella
github_username:  JVillella

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

gist:
  noscript: false

header_pages:
  - index.md

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
# permalink: pretty

plugins:
- jekyll-optional-front-matter
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
